### ISSUE TITLE
Weekly "update in Tumbleweed" posts - reverse order?

### ISSUE THREAD

**Issue by JohnVeness** [openSUSE/news-o-o#164]
Hi. I realise this is more of a content question than a technical issue with the site - please direct me elsewhere if more appropriate.

Regarding the weekly "update in Tumbleweed" posts, e.g. https://news.opensuse.org/2023/04/28/gear-grep-gtk-up-in-tw/

Within each post, the snapshots during the week are discussed in reverse chronological order, i.e. the most recent first, followed by the previous day, 2 days ago etc.

Is there a particular reason for this? This is probably subjective, but for me this reads rather oddly - I'd expect each post to go through the week's snapshots in forward chronological order.

Thanks for reading this! And thanks for the posts in the first place - despite their order, I find them informative and helpful :)

**Comment by ddemaio** [comment]
Hi @JohnVeness 
Thank you for reading the TW updates. I write these on a weekly basis when I can, but with a busy schedule the next one will be in a couple weeks. 

My approach to the chronological order is that the most recent snapshot seems to be the most newsworthy for most because it is likely to be the packages that update if someone reads the blog and decides to 'zypper dup' It also allows for me to plug in a paragraph of the latest snapshot at the top as sometimes a snapshot will be released between the time I start writing it and plan to publish. Depending on what packages update in the snapshot, I might have to rework the headline.

It's really just the approach I take based on the journalism background I have; that being a news cycle is only relevant to immediacy. I hope this clarifies any questions you might have and I'd also encourage reading the TW review on the factory mailing list https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/  This happens every week or two and gives a bit of forward looking insight.
