### ISSUE TITLE
Warning: Empty `slug` generated for ''

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/news-o-o#46]
After updated to jekyll 4.1, I run:

```
bundle exec jekyll serve
```

And got a lot of warnings:
```
Warning: Empty `slug` generated for ''.
Warning: Empty `slug` generated for ''.
Warning: Empty `slug` generated for ''.
...
```

It doesn't seem to affect the site, but good to fix.

Upstream issue https://github.com/jekyll/jekyll/issues/8259

**Comment by Ana06** [comment]
@guoyunhe this is not a problem upstream. Jekyll is complaining because is called with an empty string, which is exactly what happens [here](https://github.com/openSUSE/jekyll-theme/blob/master/_includes/header.html#L40) because we have a blog post with an empty category:
`{ category_name | slugify }`

I have removed the empty category in https://github.com/openSUSE/news-o-o/pull/66, which fix the issue.

I'll comment in jekyll/jekyll#8259, as I think that issue can be closed.
